<a href="https://colab.research.google.com/github/Louis5228/Mechine-Learning/blob/main/309512014_HW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [83]:
import os
from google.colab import drive
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np
import math
from numpy.linalg import inv, pinv
drive.mount('/content/gdrive')

data = pd.read_csv("/content/gdrive/My Drive/Machine_Learning/HW2/dataset/data.csv")
data = np.array(data)
x = data[:, :1]
t = data[:, 1:]

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [84]:
M = 3
s = 0.6
N_list = [5, 10, 30, 80]
beta = 1
m0 = np.zeros((M,1))
s0_inv = math.pow(10,-6)*np.eye(M)

def sigmoid_f(a):
  return 1 / (1 + np.exp(-a))

def cal_phi(x):
  phi = np.empty([len(x),0])
  for j in range(M):
    mu = 2*j / M
    phi = np.hstack((phi, sigmoid_f((x - mu) / s)))
  return phi

def posterior_dist(m0, s0_inv, beta, phi, t):
  sN_inv = s0_inv + beta*np.dot(phi.T, phi)
  sN = inv(sN_inv)
  mN = np.dot(sN, (np.dot(s0_inv, m0) + beta*np.dot(phi.T, t)))
  return mN, sN

for N in N_list:
  x_temp = x[:N]
  t_temp = t[:N]
  mN, sN = posterior_dist(m0, s0_inv, beta, cal_phi(x_temp), t_temp)
  print("Data size:", N, "\nmean:\n", mN, "\nconvariance:\n", sN, "\n")


Data size: 5 
mean:
 [[ 15.3918259 ]
 [-27.24893207]
 [ 13.76463907]] 
convariance:
 [[ 269.04934203 -577.62671303  361.07317844]
 [-577.62671303 1261.47181152 -803.66739994]
 [ 361.07317844 -803.66739994  523.15065575]] 

Data size: 10 
mean:
 [[ 15.3974152 ]
 [-27.40629378]
 [ 14.00195039]] 
convariance:
 [[ 168.04688541 -341.15540081  202.52975073]
 [-341.15540081  706.27405822 -429.99999167]
 [ 202.52975073 -429.99999167  270.34416277]] 

Data size: 30 
mean:
 [[ 19.22763557]
 [-35.78002777]
 [ 19.39941303]] 
convariance:
 [[ 24.12006368 -54.9357445   37.11498943]
 [-54.9357445  127.7793514  -88.33383235]
 [ 37.11498943 -88.33383235  62.70588466]] 

Data size: 80 
mean:
 [[ 18.85466897]
 [-34.50677874]
 [ 18.21950653]] 
convariance:
 [[  6.59105561 -14.94010939  10.02307411]
 [-14.94010939  34.88289614 -24.16334859]
 [ 10.02307411 -24.16334859  17.34855927]] 

